In [187]:
import os

import numpy as np
from PIL import Image
import cv2
import matplotlib.pyplot as plt
from plyfile import *
import glob
import time
from kitti360scripts.helpers.project import Camera, CameraPerspective
from kitti360scripts.helpers.ply import *

In [188]:
#Main path

KITTI360Path="/media/ren/EXTERNAL_USB/KITTI360_DATASET/"

print(KITTI360Path)





/media/ren/EXTERNAL_USB/KITTI360_DATASET/


In [189]:

#perspective file
perspective=os.path.join(KITTI360Path,"calibration/perspective.txt")
#calib_cam2pose file
calib_cam2pose=os.path.join(KITTI360Path,"calibration/calib_cam_to_pose.txt")

In [180]:
# K,width,height=CameraPerspective.load_intrinsics(perspective)

In [190]:
#intrinsic matrix and recification matrix load from perspective
def load_intrinsics(intrinsic_file):
    #This function is camera Intrinsic matrix, P_rect_00 and R_rect_00
    with open(intrinsic_file) as f:
        intrinsics = f.read().splitlines()
    for line in intrinsics:
        line = line.split(' ')
        #3x4 intrinsic matrix from perspective.txt
        if line[0] == 'P_rect_00:' :
            IntrinsicMat = [float(x) for x in line[1:]]
            IntrinsicMat = np.reshape(IntrinsicMat, [3,4])
 

    return IntrinsicMat#, R_rectMat,# calic2p

In [191]:
IntrinsicMat=load_intrinsics(perspective)#read intrinsic matrix and rectification matrix
IntrinsicMat

array([[552.554261,   0.      , 682.049453,   0.      ],
       [  0.      , 552.554261, 238.769549,   0.      ],
       [  0.      ,   0.      ,   1.      ,   0.      ]])

In [249]:
# #ply read
def read_ply(seq,str):
    """ read XYZ point cloud from filename PLY file """
    pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_00%s_sync/'%seq,str)
    # print(pc_path)
    filelist = os.listdir(pc_path)
    filelist=sorted(filelist)
    # print('file',filelist)
    print(len(filelist))
    for i in range(1):
    # for i in range(10):
        # print(filelist[i],i)
        plydata = PlyData.read(os.path.join(pc_path,filelist[i]))
        # print('plydata',plydata)
        pc_x = np.expand_dims(np.array(plydata['vertex']['x']),1)
        pc_y = np.expand_dims(np.array(plydata['vertex']['y']),1)
        pc_z = np.expand_dims(np.array(plydata['vertex']['z']),1)
        pc_r = np.expand_dims(np.array(plydata['vertex']['red']),1)#.reshape()
        pc_g = np.expand_dims(np.array(plydata['vertex']['green']),1)
        pc_b = np.expand_dims(np.array(plydata['vertex']['blue']),1)
        # print(pc_x.shape,pc_y.shape,pc_z.shape)
        pc=np.concatenate((pc_x,pc_y,pc_z),1)
        # print('pcc',pc)
        pc=np.transpose(np.concatenate((pc_x,pc_y,pc_z),1))
        # print('pc',pc)
        pc_color=np.transpose(np.concatenate((pc_r,pc_g,pc_b),1))
        
        if i == 0:
            pc_0=pc
            pc_c0=pc_color
            pcMat=pc_0
            pcMat_RGB=pc_c0
            # print('pc_0',pc_0.shape)#3323827
            # print('pc_c0',pc_c0)
        # print(pc_0)
        else:
            pcMat=np.array(np.concatenate([pcMat,pc],axis=1))
            
            
        # pcMat=np.concatenate([pcMat,pc],axis=0)
            pcMat_RGB=np.array(np.concatenate([pcMat_RGB,pc_color],axis=1))
    # print(pc.shape)
    # pcMat
        # print('pcMat',pcMat.shape)
    return pcMat,pcMat_RGB

pcMat,pcMatC=read_ply("05","static")
# pcMat=pcMat[:,:100]
print('pcMat',pcMat.shape)
print('pcMatC',pcMatC.shape)


24
pcMat (3, 3691047)
pcMatC (3, 3691047)


In [125]:
# # #ply read, one 1 file
# def read_ply(seq,str):
#     """ read XYZ point cloud from filename PLY file """
#     pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_00%s_sync/'%seq,str)
#     # print(pc_path)
#     filelist = os.listdir(pc_path)
#     filelist=sorted(filelist)
#     # print('file',filelist)
#     print(len(filelist))
#     # for i in range(filelist):
#     for i in range(1):
#         # print(filelist[i],i)
#         plydata = PlyData.read(os.path.join(pc_path,filelist[i]))
#         # print('plydata',plydata)
#         pc_x = np.expand_dims(np.array(plydata['vertex']['x']),1)
#         pc_y = np.expand_dims(np.array(plydata['vertex']['y']),1)
#         pc_z = np.expand_dims(np.array(plydata['vertex']['z']),1)
#         pc_r = np.expand_dims(np.array(plydata['vertex']['red']),1)#.reshape()
#         pc_g = np.expand_dims(np.array(plydata['vertex']['green']),1)
#         pc_b = np.expand_dims(np.array(plydata['vertex']['blue']),1)
#         # print(pc_x.shape,pc_y.shape,pc_z.shape)
#         pc=np.concatenate((pc_x,pc_y,pc_z),1)
#         # print('pcc',pc)
#         pc=np.transpose(np.concatenate((pc_x,pc_y,pc_z),1))
#         # print('pc',pc)
#         pc_color=np.transpose(np.concatenate((pc_r,pc_g,pc_b),1))
        
#         if i == 0:
#             pc_0=pc
#             pc_c0=pc_color
#             pcMat=pc_0
#             pcMat_RGB=pc_c0
#             # print('pc_0',pc_0.shape)#3323827
#             # print('pc_c0',pc_c0)
#         # print(pc_0)
#         else:
#             pcMat=np.array(np.concatenate([pcMat,pc],axis=1))
            
            
#         # pcMat=np.concatenate([pcMat,pc],axis=0)
#             pcMat_RGB=np.array(np.concatenate([pcMat_RGB,pc_color],axis=1))
#     # print(pc.shape)
#     # pcMat
#         # print('pcMat',pcMat.shape)
#     return pcMat,pcMat_RGB

# pcMat,pcMatC=read_ply("05","static")
# # pcMat=pcMat[:,:100]
# print('pcMat',pcMat.shape)


In [126]:
# # #ply read
# def read_oneply(seq,str):
#     """ read XYZ point cloud from filename PLY file """
#     pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_00%s_sync/'%seq,str,'000002_000357.ply')
#     # print(pc_path)
#     # filelist = os.listdir(pc_path)
#     # filelist=sorted(filelist)
#     # print('file',filelist)
#     # print(len(filelist))
#     # print(filelist[i],i)
#     plydata = PlyData.read(pc_path)
#     # print('plydata',plydata)
#     pc_x = np.expand_dims(np.array(plydata['vertex']['x']),1)
#     pc_y = np.expand_dims(np.array(plydata['vertex']['y']),1)
#     pc_z = np.expand_dims(np.array(plydata['vertex']['z']),1)
#     pc_r = np.expand_dims(np.array(plydata['vertex']['red']),1)#.reshape()
#     pc_g = np.expand_dims(np.array(plydata['vertex']['green']),1)
#     pc_b = np.expand_dims(np.array(plydata['vertex']['blue']),1)
#     # print(pc_x.shape,pc_y.shape,pc_z.shape)
#     pc=np.concatenate((pc_x,pc_y,pc_z),1)
#     # print('pcc',pc)
#     pc=np.transpose(np.concatenate((pc_x,pc_y,pc_z),1))
#     # print('pc',pc)
#     pc_color=np.transpose(np.concatenate((pc_r,pc_g,pc_b),1))
    
    
#     # pc_0=pc
#     # pc_c0=pc_color
#     # pcMat=pc_0
#     # pcMatC=pc_c0
#         # print('pc_0',pc_0)
#         # print('pc_c0',pc_c0)
#     # print(pc_0)
#     # pcMat=np.array(np.concatenate([pcMat,pc],axis=1))
        
        
#     # pcMat=np.concatenate([pcMat,pc],axis=0)
#     # pcMat_RGB=np.array(np.concatenate([pcMatC,pc_color],axis=1))
#     # print(pc.shape)
#     # pcMat
#     return pc,pc_color

# pcMat,pcMatC=read_oneply("05","static")
# print('pcMat',pcMat,pcMat.shape)

In [127]:
# pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_0000_sync/static/000372_000610.ply')
# data=read_oneply(pc_path, "static")
# print(data,data.shape)

# pcMat= np.vstack((data['x'], data['y'], data['z']))
# pcMatC= np.vstack((data['red'], data['green'], data['blue']))
# print(pcMat,pcMat.shape,pcMatC,pcMatC.shape)

In [250]:
print('pcMat',pcMatC[:,9000:10000],pcMatC[:,9000:10000].shape)

pcMat [[128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]] (3, 1000)


In [238]:
import sys
print(sys.getsizeof(pcMat)/1024**2)

0.0001068115234375


In [ ]:
# T

In [264]:
def world2image(pose_array_list, pcMat, pcMatC,IntrinsicMat):
    #This function is to open poses file 
    #cam2poses file
    
    #input: row of cam0_to_world, 1x16 
    #input: point cloud matrix, 3xN
    # warning: pcMat will be destroyed!
    """
    posespath=os.path.join(KITTI360Path,'data_poses/2013_05_28_drive_00%s_sync/'%seq,"cam0_to_world.txt")
    # print('poses',posespath)
    
    with open(posespath) as f:
        posesdata = f.read().splitlines()
    start_time=time.time()
    for line in posesdata:
        line = line.split(' ')
        # print('line',line)
        # for i in line:
        if '' in line:
            line.remove('')
        frame.append(int(line[0]))
        frameID=len(frame)
        print(frameID)
        pcMat,pcMatC=read_ply("00",'static')
    """
        

        # print('line',line)
        # print('line',line[1:])

        # print('frame',line[0])
        # print('len line',len(line))  
    #所有的R和T的来源，每个点的平移和旋转
    pose=np.array([float(x) for x in pose_array_list]).reshape(4,4)
    print('pose',pose)
    R=pose[:3,:3].reshape(3,3)
    T=pose[:3,3].reshape(3,1)
    #R是3✖3，T是3x1。points最终结果为3x1
    print('R',R,R.shape)
    print('T',T,T.shape)
    # print('R',R,R.shape)
    
    # print(int(pcMat.shape[1]))
    
    #R:3x3, pcMat:3xN, T:扩展为3xN    
    # print('T.shape',(np.repeat(np.expand_dims(T,axis=1),pcMat.shape[1],axis=1)).shape)
    # print('mat shape',pcMat[:,:].shape)
    # print('R shape',(R.T).shape)
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(np.expand_dims(T,axis=1),pcMat.shape[1],axis=1)))
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(T,pcMat.shape[1],axis=1)))
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(T,pcMat.shape[1],axis=1)))
        # points_local.append(points)
    # print('pcMat',pcMat[:,:].shape)
    # print('T',T[:,:],T[:,:].shape)
    print('transfer',((pcMat-T)),((pcMat-T)).shape)
    # Pworld=
    print("transpose R",np.linalg.inv(R))
    points_local=np.matmul(R.T,(pcMat-T))
    print('local points',points_local)    
    #local points = 3xN
    print('3x3 Intrinsic',IntrinsicMat[:3,:3])
    print('Intrinsic',IntrinsicMat)
    proj_points=np.matmul(IntrinsicMat[:3,:3],points_local)
    print('image points',proj_points[:,:100])
    del pcMat
    # proj_points.append(points_proj)
    print((proj_points[2,:]>0).shape)
    print(proj_points.shape)
    idx = proj_points[2,:]>0
    proj_points = proj_points[:,idx]
    pcMatC= pcMatC[:,idx]
    print('filter1',proj_points)
    #proj_points[2,:][proj_points[2,:]==0] = -1e-6
    #depth=proj_points[2,:]
    
    #depth[depth==0]= -1e-6
    
    #print(sys.getsizeof(proj_points))

    #normalized image coordinates
    u = np.round(proj_points[0,:]/np.abs(proj_points[2,:]))#.astype(np.int)
    v = np.round(proj_points[1,:]/np.abs(proj_points[2,:]))#.astype(np.int)
        
        # U.append(u)
        # V.append(v)
        # d.append(depth)
        # end_time=time.time()
        # print('pose',pose)
        # pose=np.array(np.concatenate((pose, np.array([0.,0.,0.,1.]).reshape(1,4))))
        # print('pose',pose)
        # print('time',end_time-start_time)
        # poses.appened(pose)
    # print("poses",poses)
            # calculate u, v depth
    print('u',u,u.shape)
    print('v',v,u.shape)
    print('d',proj_points[2,:])
    return u,v,proj_points[2,:],pcMatC



In [265]:

# pcMat,pcMatC=read_oneply("05","static")
pcMat,pcMatC=read_ply("05","static")
# pcMat=pcMat[:,9000:10000]
# pcMatC=pcMatC[:,9000:10000]
print('pcMatC',pcMatC,pcMatC.shape)
posespath=os.path.join(KITTI360Path,"data_poses/2013_05_28_drive_0005_sync/cam0_to_world.txt")
IntrinsicMat=load_intrinsics(perspective)#read intrinsic matrix and rectification matrix
# print('IntrinsicMat',IntrinsicMat,IntrinsicMat.shape)
poses=np.loadtxt(posespath)
frame=poses[:,0]
pose_initial=poses[0,1:]

# print('inital',pose_initial)
u,v,d,pcMatC=world2image(pose_initial, pcMat,pcMatC, IntrinsicMat)
del pcMat

# print('u',u,u.shape)
# print('v',v,v.shape)
# print('depth',d,d.shape)
# del u,v,d

24
pcMatC [[128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]] (3, 3691047)
pose [[ 9.751520e-01  7.231276e-02 -2.094060e-01  3.418926e+03]
 [ 2.197550e-01 -1.959833e-01  9.556660e-01 -3.000540e+03]
 [ 2.806700e-02 -9.779376e-01 -2.070040e-01  2.448654e+02]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
R [[ 0.975152    0.07231276 -0.209406  ]
 [ 0.219755   -0.1959833   0.955666  ]
 [ 0.028067   -0.9779376  -0.207004  ]] (3, 3)
T [[ 3418.926 ]
 [-3000.54  ]
 [  244.8654]] (3, 1)
transfer [[-150.88986719 -150.78049219 -150.76291406 ... -145.71555078
  -145.76755273 -145.7944082 ]
 [ -20.83695313  -20.95511719  -20.81839844 ...  -11.79911133
   -11.55619141  -11.57035156]
 [  -8.32890098   -8.31109397   -8.31429832 ...   -5.84640281
    -6.59179465   -6.48930137]] (3, 3691047)
transpose R [[ 0.97515055  0.21975492  0.02806675]
 [ 0.07231281 -0.19598287 -0.97793713]
 [-0.20940591  0.95566693 -0.20700449]]
local points [[-151.95334767 -

In [110]:
max(u)

135787662425.0

In [266]:
pcMat = None

In [ ]:
# def transfer4frame(seq,pcMat):
#     posespath=os.path.join(KITTI360Path,'data_poses/2013_05_28_drive_00%s_sync/'%seq,"cam0_to_world.txt")
#     # print('poses',posespath)
#     frame=[]
#     U=[]
#     V=[]
#     D=[]
#     # with open(posespath) as f:
#     #     posesdata = f.read().splitlines()
#     #     # print(posesdata)
#     # # start_time=time.time()
#     # for line in posesdata:
#     #     line = line.split(' ')
#     #     print('line',line)
#     #     # for i in line:
#     #     if '' in line:
#     #         line.remove('')
#     #     print('l',line)
#     #     frame.append(int(line[0]))
#     #     frameID=len(frame)
#     #     print("frameID",frameID)
#     poses=np.loadtxt(posespath)    
#     frame=poses[:,0]
#     poses=poses[:,1:]
#     print('poses',poses.shape)
#     for i in range(poses.shape[0]): 
  
#         u,v,depth=world2image(poses[i,:], pcMat)
#         frame[i]
#         U.append(u.T)
#         V.append(v.T)
        
#         D.append(depth.T)    

        
        
#     return U,V,D
    

In [ ]:
# u,v,depth=transfer4frame('00', pcMat)

In [296]:

def uvdepth_to_image(u, v, depth, image_x=1408, image_y=376):
    # input u: N*1
    # input v: N*1
    # input depth: N*1
    # return: image image_x*image_y
    
    idx = np.where((u >= 0) & (u < image_x) & (v >= 0) & (v < image_y) & (depth >= 0))
    image = np.zeros((image_x, image_y))
    
    for i in idx:
        x = u[i]
        y = v[i]
        d = depth[i]
        image[x,y] = d
    return image

def uvRGBD_to_image(u, v,  depth, rgb_mat, image_x=1408, image_y=376):
    # input u: N*1
    # input v: N*1
    # input rgb_mat: N*3
    # return: image: image_x*image_y*3
    #u -= 200
    #v -= 80
    idx = np.where((u >= 0) & (u < image_x) & (v >= 0) & (v < image_y) & (depth >= 0))
    # print(idx[0].shape)
    # print(idx)
    image = np.zeros((image_x, image_y, 3))
    image_depth = np.ones((image_x, image_y))*np.inf
    # rgb_mat=rgb_mat.transpose((1,2,0))
    # print('image 0',image)
    # print("rgb",rgb_mat.shape)
    # print("u",u.shape)
    # print('idx',idx[0])
    # print(len(idx[0]))
    for i in idx[0]:
        x = int(u[i])
        y = int(v[i])
        rgb = rgb_mat[i,:]
        # print('rgb',rgb.shape)
        d = depth[i]
        # print((x,y,rgb,d))
        if d < image_depth[x,y]:
            # print(rgb)
            image[x, y, :] = np.array([rgb[2],rgb[1],rgb[0]])#bgr
            image_depth[x,y] = d
    return image, image_depth
    
    


In [259]:
image1[image1>0]

array([161., 152., 126., ...,  11.,  13.,   9.])

In [297]:
image1, image_depth=uvRGBD_to_image(u, v, d, pcMatC.T, image_x=1408, image_y=376)
# print(pcMatC.T)
# print(77)
# print(u)

cv2.imwrite('05_frame_00.png',image1.transpose((1,0,2)))

True

Now, once we get points on frame, we are going to draw them. Using a huge matrix as a plot graph, set the boundary of image(1408,376), put u,v on the image, but ignore all the depth <0. if u and v are same, choose the smallest depth to save. Drawing graph with 3 channel RGB value.  

画图工作：首先拥有像素坐标系的信息，图像像素u和v，深度信息depth，颜色信息RGB。使用一个巨大的空矩阵，作为图像，像素的大小为图片的大小。接着将3D得到的点放入矩阵中，其中，u和v超过图像边缘的点舍去，深度小于0的点舍去。

In [ ]:
imageMat=np.zeros(1408,376)

TypeError: Cannot interpret '376' as a data type