In [1]:
import os

import numpy as np
from PIL import Image
import cv2
import matplotlib.pyplot as plt
from plyfile import *
import glob
import time
from kitti360scripts.helpers.project import Camera, CameraPerspective
from kitti360scripts.helpers.ply import *

In [2]:
#Main path
KITTI360Path="/media/ren/Seagate/KITTI360_DATASET/"

print(KITTI360Path)


/media/ren/Seagate/KITTI360_DATASET/


In [3]:
#image pixel 
width=1408 #width
height=376 #height
#template pixel
tempWl=100 #width
tempWr=1300
tempHu=10 #height
tempHd=350
#index of frame
frameId=0
#maximum and minimum value within matrix
max_v=0
min_v=0
# cam2pose=[] #unrecified camera to GPU/IMU matrix 
poses=[] #GPU/IMU to world transform matrix
R_rectMat=np.eye(4)#recification matrix
pcMat=[]#point cloud matrix
pcMatC=[]#point cloud color matrix
frame=[]#frame index
proj_points=[] #camera coordinate
U=[]#image coordinate u
V=[]#image coordinate v
D=[]#image coordinate depth

#perspective file
perspective=os.path.join(KITTI360Path,"calibration/perspective.txt")
#calib_cam2pose file
calib_cam2pose=os.path.join(KITTI360Path,"calibration/calib_cam_to_pose.txt")

In [4]:
#intrinsic matrix and recification matrix load from perspective
def load_intrinsics(intrinsic_file):
    #This function is camera Intrinsic matrix, P_rect_00 and R_rect_00
    with open(intrinsic_file) as f:
        intrinsics = f.read().splitlines()
    for line in intrinsics:
        line = line.split(' ')
        #3x4 intrinsic matrix from perspective.txt
        if line[0] == 'P_rect_00:' :
            IntrinsicMat = [float(x) for x in line[1:]]
            IntrinsicMat = np.reshape(IntrinsicMat, [3,4])
 
        #rectification matrix: eye(4) with the left up 3x3 filled with numbers from perspective.txt
        # elif line[0] == 'R_rect_00:':
        #     # R_rect = np.eye(4) 
        #     R_rectMat[:3,:3] = np.array([float(x) for x in line[1:]]).reshape(3,3)

            
    # print("intrinsic",IntrinsicMat)
    # print("R_rect",R_rectMat)
    # print("cam2pose calib",calic2p)
    return IntrinsicMat#, R_rectMat,# calic2p

In [5]:
IntrinsicMat=load_intrinsics(perspective)#read intrinsic matrix and rectification matrix
IntrinsicMat
# R_rectMat.shape

array([[552.554261,   0.      , 682.049453,   0.      ],
       [  0.      , 552.554261, 238.769549,   0.      ],
       [  0.      ,   0.      ,   1.      ,   0.      ]])

In [6]:
#ply read
def read_ply(seq,str):
    """ read XYZ point cloud from filename PLY file """
    pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_00%s_sync/'%seq,str)
    # print(pc_path)
    filelist = os.listdir(pc_path)
    filelist=sorted(filelist)
    # print('file',filelist)
    # print(len(filelist))
    for i in range(len(filelist)):
        # print(filelist[i],i)
        plydata = PlyData.read(os.path.join(pc_path,filelist[i]))
        # print('plydata',plydata)
        pc_x = np.expand_dims(np.array(plydata['vertex']['x']),1)
        pc_y = np.expand_dims(np.array(plydata['vertex']['y']),1)
        pc_z = np.expand_dims(np.array(plydata['vertex']['z']),1)
        pc_r = np.expand_dims(np.array(plydata['vertex']['red']),1)#.reshape()
        pc_g = np.expand_dims(np.array(plydata['vertex']['green']),1)
        pc_b = np.expand_dims(np.array(plydata['vertex']['blue']),1)
        # print(pc_x.shape,pc_y.shape,pc_z.shape)
        pc=np.concatenate((pc_x,pc_y,pc_z),1)
        # print('pcc',pc)
        pc=np.transpose(np.concatenate((pc_x,pc_y,pc_z),1))
        # print('pc',pc)
        pc_color=np.transpose(np.concatenate((pc_r,pc_g,pc_b),1))
        
        if i == 0:
            pc_0=pc
            pc_c0=pc_color
            pcMat=pc_0
            pcMatC=pc_c0
            # print('pc_0',pc_0)
            # print('pc_c0',pc_c0)
        # print(pc_0)
        pcMat=np.array(np.concatenate([pcMat,pc],axis=1))
            
            
        # pcMat=np.concatenate([pcMat,pc],axis=0)
        pcMat_RGB=np.array(np.concatenate([pcMatC,pc_color],axis=1))
    # print(pc.shape)
    # pcMat
    return pcMat,pcMat_RGB

pcMat,pcMatC=read_ply("00","static")
print('pcMat',pcMat,pcMat.shape)

KeyboardInterrupt: 

In [7]:
#ply read
def read_oneply(seq,str):
    """ read XYZ point cloud from filename PLY file """
    pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_00%s_sync/'%seq,str,'000002_000385.ply')
    # print(pc_path)
    # filelist = os.listdir(pc_path)
    # filelist=sorted(filelist)
    # print('file',filelist)
    # print(len(filelist))
    # print(filelist[i],i)
    plydata = PlyData.read(pc_path)
    # print('plydata',plydata)
    pc_x = np.expand_dims(np.array(plydata['vertex']['x']),1)
    pc_y = np.expand_dims(np.array(plydata['vertex']['y']),1)
    pc_z = np.expand_dims(np.array(plydata['vertex']['z']),1)
    pc_r = np.expand_dims(np.array(plydata['vertex']['red']),1)#.reshape()
    pc_g = np.expand_dims(np.array(plydata['vertex']['green']),1)
    pc_b = np.expand_dims(np.array(plydata['vertex']['blue']),1)
    # print(pc_x.shape,pc_y.shape,pc_z.shape)
    pc=np.concatenate((pc_x,pc_y,pc_z),1)
    # print('pcc',pc)
    pc=np.transpose(np.concatenate((pc_x,pc_y,pc_z),1))
    # print('pc',pc)
    pc_color=np.transpose(np.concatenate((pc_r,pc_g,pc_b),1))
    
    
    # pc_0=pc
    # pc_c0=pc_color
    # pcMat=pc_0
    # pcMatC=pc_c0
        # print('pc_0',pc_0)
        # print('pc_c0',pc_c0)
    # print(pc_0)
    # pcMat=np.array(np.concatenate([pcMat,pc],axis=1))
        
        
    # pcMat=np.concatenate([pcMat,pc],axis=0)
    # pcMat_RGB=np.array(np.concatenate([pcMatC,pc_color],axis=1))
    # print(pc.shape)
    # pcMat
    return pc,pc_color

pcMat,pcMatC=read_oneply("00","static")
print('pcMat',pcMat,pcMat.shape)

pcMat [[1000.8657 1000.8753 1000.9065 ... 1001.1812 1001.1264 1001.1545]
 [3820.2976 3820.3816 3820.6013 ... 3820.5242 3820.5708 3820.547 ]
 [ 116.2225  116.193   116.188  ...  117.0209  117.1629  117.3406]] (3, 3323827)


In [8]:
# pc_path=os.path.join(KITTI360Path,'data_3d_semantics/2013_05_28_drive_0000_sync/static/000002_000385.ply')
# # data=read_ply(pc_path, triangular_mesh=False)
# print(data,data.shape)
# # pcMat=(data[:,6])
# pcMat= np.vstack((data['x'], data['y'], data['z']))
# pcMatC= np.vstack((data['red'], data['green'], data['blue']))
# print(pcMat,pcMat.shape,pcMatC,pcMatC.shape)

In [9]:
print('pcMat',pcMat,pcMat.shape)

pcMat [[1000.8657 1000.8753 1000.9065 ... 1001.1812 1001.1264 1001.1545]
 [3820.2976 3820.3816 3820.6013 ... 3820.5242 3820.5708 3820.547 ]
 [ 116.2225  116.193   116.188  ...  117.0209  117.1629  117.3406]] (3, 3323827)


In [10]:
import sys
print(sys.getsizeof(pcMat)/1024**2)

0.0001068115234375


In [12]:
def world2image(pose_array_list, pcMat, IntrinsicMat):
    #This function is to open poses file 
    #cam2poses file
    
    #input: row of cam0_to_world, 1x16 
    #input: point cloud matrix, 3xN
    # warning: pcMat will be destroyed!
    """
    posespath=os.path.join(KITTI360Path,'data_poses/2013_05_28_drive_00%s_sync/'%seq,"cam0_to_world.txt")
    # print('poses',posespath)
    
    with open(posespath) as f:
        posesdata = f.read().splitlines()
    start_time=time.time()
    for line in posesdata:
        line = line.split(' ')
        # print('line',line)
        # for i in line:
        if '' in line:
            line.remove('')
        frame.append(int(line[0]))
        frameID=len(frame)
        print(frameID)
        pcMat,pcMatC=read_ply("00",'static')
    """
        

        # print('line',line)
        # print('line',line[1:])

        # print('frame',line[0])
        # print('len line',len(line))  
    #所有的R和T的来源，每个点的平移和旋转
    pose=np.array([float(x) for x in pose_array_list]).reshape(4,4)
    R=pose[:3,:3].reshape(3,3)
    T=pose[:3,3].reshape(3,1)
    #R是3✖3，T是3x1。points最终结果为3x1
    print('R',R,R.shape)
    print('T',T,T.shape)
    # print('R',R,R.shape)
    
    # print(int(pcMat.shape[1]))
    
    #R:3x3, pcMat:3xN, T:扩展为3xN    
    # print('T.shape',(np.repeat(np.expand_dims(T,axis=1),pcMat.shape[1],axis=1)).shape)
    # print('mat shape',pcMat[:,:].shape)
    # print('R shape',(R.T).shape)
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(np.expand_dims(T,axis=1),pcMat.shape[1],axis=1)))
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(T,pcMat.shape[1],axis=1)))
    # points_local=np.matmul(R.T,(pcMat[:,:]-np.repeat(T,pcMat.shape[1],axis=1)))
        # points_local.append(points)
    print('pcMat',pcMat[:,:],pcMat[:,:].shape)
    print('T',T[:,:],T[:,:].shape)
    print('transfer',(pcMat[:,:]-T[:,:]),(pcMat[:,:]-T[:,:]).shape)
    points_local=np.matmul(R.T,(pcMat[:,:]-T[:,:]))
    # print('local points',points_local)    ?/
    #local points = 3xN
    # print('3x3 Intrinsic',IntrinsicMat[:3,:3])
    # print('Intrinsic',IntrinsicMat)
    proj_points=np.matmul(IntrinsicMat[:3,:3],points_local)
    print('image points',proj_points)
    del pcMat
    
    # proj_points.append(points_proj)
    
    proj_points[2,:][proj_points[2,:]<=0] = -1e-6
    # filter = proj_points[:,proj_points[2,:]>=0]
    # depth=proj_points[2,:]
    # print('f',filter)
    u=proj_points[0,:]
    v=proj_points[1,:]
    print(u)
    print(v)
    #depth[depth==0]= -1e-6
    
    #print(sys.getsizeof(proj_points))

    #normalized image coordinates
    u = np.round(proj_points[0,:]/np.abs(proj_points[2,:])).astype(np.int)
    v = np.round(proj_points[1,:]/np.abs(proj_points[2,:])).astype(np.int)
        
        # U.append(u)
        # V.append(v)
        # d.append(depth)
        # end_time=time.time()
        # print('pose',pose)
        # pose=np.array(np.concatenate((pose, np.array([0.,0.,0.,1.]).reshape(1,4))))
        # print('pose',pose)
        # print('time',end_time-start_time)
        # poses.appened(pose)
    # print("poses",poses)
            # calculate u, v depth
    print('u',u)
    print('v',v)
    print('d',proj_points[2,:])
    return u,v,proj_points[2,:]



In [13]:

# pcMat,pcMatC=read_oneply("00","static")
# print('pcMat',pcMat,pcMat.shape)
posespath=os.path.join(KITTI360Path,'data_poses/2013_05_28_drive_0000_sync/',"cam0_to_world.txt")
IntrinsicMat=load_intrinsics(perspective)#read intrinsic matrix and rectification matrix
# print('IntrinsicMat',IntrinsicMat,IntrinsicMat.shape)
poses=np.loadtxt(posespath)
frame=poses[:,0]
pose_initial=poses[0,1:]

print('inital',pose_initial)
u,v,d=world2image(pose_initial, pcMat, IntrinsicMat)
# del pcMat

# print('u',u,u.shape)
# print('v',v,v.shape)
# print('depth',d,d.shape)
u,v,d

inital [-9.384250e-01  1.471056e-02 -3.451720e-01  8.456584e+02  3.454490e-01
  5.439153e-02 -9.368600e-01  3.723648e+03  4.993000e-03 -9.984115e-01
 -5.612300e-02  1.159991e+02  0.000000e+00  0.000000e+00  0.000000e+00
  1.000000e+00]
R [[-0.938425    0.01471056 -0.345172  ]
 [ 0.345449    0.05439153 -0.93686   ]
 [ 0.004993   -0.9984115  -0.056123  ]] (3, 3)
T [[ 845.6584]
 [3723.648 ]
 [ 115.9991]] (3, 1)
pcMat [[1000.8657 1000.8753 1000.9065 ... 1001.1812 1001.1264 1001.1545]
 [3820.2976 3820.3816 3820.6013 ... 3820.5242 3820.5708 3820.547 ]
 [ 116.2225  116.193   116.188  ...  117.0209  117.1629  117.3406]] (3, 3323827)
T [[ 845.6584]
 [3723.648 ]
 [ 115.9991]] (3, 1)
transfer [[155.20732266 155.21690518 155.24809414 ... 155.52281338 155.46800381
  155.49607998]
 [ 96.64960742  96.7335918   96.95331836 ...  96.87616992  96.92280078
   96.89911914]
 [  0.22340366   0.19390079   0.18890354 ...   1.02179691   1.16380283
    1.34149906]] (3, 3323827)
image points [[-1.60336513e+05 -1.

(array([-160336512585, -160380323302, -160502121569, ..., -160704261071,
        -160688876677, -160705744703]),
 array([-30371478716, -30371781873, -30413822725, ..., -30889941023,
        -30975143169, -31073055248]),
 array([-1.e-06, -1.e-06, -1.e-06, ..., -1.e-06, -1.e-06, -1.e-06]))

In [179]:
print(u)

[-160336512585 -160380323302 -160502121569 ... -160704261071 -160688876677
 -160705744703]


In [14]:
pcMat = None

In [14]:
def transfer4frame(seq,pcMat):
    posespath=os.path.join(KITTI360Path,'data_poses/2013_05_28_drive_00%s_sync/'%seq,"cam0_to_world.txt")
    # print('poses',posespath)
    frame=[]
    U=[]
    V=[]
    D=[]
    # with open(posespath) as f:
    #     posesdata = f.read().splitlines()
    #     # print(posesdata)
    # # start_time=time.time()
    # for line in posesdata:
    #     line = line.split(' ')
    #     print('line',line)
    #     # for i in line:
    #     if '' in line:
    #         line.remove('')
    #     print('l',line)
    #     frame.append(int(line[0]))
    #     frameID=len(frame)
    #     print("frameID",frameID)
    poses=np.loadtxt(posespath)    
    frame=poses[:,0]
    poses=poses[:,1:]
    print('poses',poses.shape)
    for i in range(poses.shape[0]): 
  
        u,v,depth=world2image(poses[i,:], pcMat, IntrinsicMat)
        frame[i]
        U.append(u.T)
        V.append(v.T)
        
        D.append(depth.T)    

        
        
    return U,V,D
    

In [19]:
u,v,depth=transfer4frame('00', pcMat)

poses (10514, 16)


TypeError: world2image() missing 1 required positional argument: 'IntrinsicMat'

In [18]:

def uvdepth_to_image(u, v, depth, image_x=1408, image_y=376):
    # input u: N*1 
    # input v: N*1
    # input depth: N*1
    # return: image image_x*image_y
    
    idx = np.where((u >= 0) & (u < image_x) & (v >= 0) & (v < image_y) & (depth >= 0))
    image = np.zeros((image_x, image_y))
    
    for i in idx:
        x = u[i]
        y = v[i]
        d = depth[i]
        image[x,y] = d

    return image

def uvRGB_to_image(u, v,  depth, rgb_mat, image_x=1408, image_y=376):
    # input u: N*1
    # input v: N*1
    # input rgb_mat: N*3
    # return: image: image_x*image_y*3
    
    idx = np.where((u >= 0) & (u < image_x) & (v >= 0) & (v < image_y) & (depth >= 0))
    image = np.zeros((image_x, image_y, 3))
    
    for i in idx:
        x = u[i]
        y = v[i]
        rgb = rgb_mat[i,:]
        image[x, y, :] = rgb

    return image
image=uvRGB_to_image(u, v,  depth, pcMatC.T, image_x=1408, image_y=376)
cv2.imshow(image)
    
    


NameError: name 'depth' is not defined

In [17]:
image=uvRGB_to_image(u, v, d, pcMatC.T, image_x=1408, image_y=376)

Now, once we get points on frame, we are going to draw them. Using a huge matrix as a plot graph, set the boundary of image(1408,376), put u,v on the image, but ignore all the depth <0. if u and v are same, choose the smallest depth to save. Drawing graph with 3 channel RGB value.  

画图工作：首先拥有像素坐标系的信息，图像像素u和v，深度信息depth，颜色信息RGB。使用一个巨大的空矩阵，作为图像，像素的大小为图片的大小。接着将3D得到的点放入矩阵中，其中，u和v超过图像边缘的点舍去，深度小于0的点舍去。

In [ ]:
imageMat=np.zeros(1408,376)